### ISSUE TITLE
Add Grafana Loki + Promtail

### ISSUE THREAD

**Issue by pizzaluc** [Herover/itu-devops-h#116]
- [x] Add logi to monitoring server
  * Add grafana/loki container to docker-compose.yml

- [x] Add Promtail to servers that should be logged
  * Either change output from service in container to both output to stdout/stderr and to a file in a docker volume
  * Or look into this docker plugin that does automatically ships docker logs to our Logi server 
    * https://grafana.com/docs/loki/latest/clients/docker-driver/
    * https://yuriktech.com/2020/03/21/Collecting-Docker-Logs-With-Loki/
  * Consider services to log (minitwit server, grafana, prometheus, database, linux system logs, drone logs)

- [x] Change minitwit logs to a better format
  * Add a actual logger instead of using println.
  * Reference lecture slides from 22/03

**Comment by Herover** [comment]
Assigning myself to adding loki server, will try to add logs from the other services on the server to test it.
