### ISSUE TITLE
Pen-Test Our System

### ISSUE THREAD

**Issue by Herover** [Herover/itu-devops-h#126]
> Try to test for vulnerabilities in your project by using wmap, [zaproxy](https://www.zaproxy.org/getting-started/), or any of the tools in the [list of OWASP vulnerability scanning tools](https://owasp.org/www-community/Vulnerability_Scanning_Tools))
> Fix at least one vulnerability that you find; ideally one that is high in your prioritization cf. to your risk analysis

> To think about: can you find the traces of the pen test in the logs? Or of your colleagues pen-test?

**Comment by smilladion** [comment]
Tested with wmap, no vulnerabilities.

**Comment by smilladion** [comment]
Tested with Skipfish, gave back three major vulnerabilities... namely Query Injection, Shell Injection and Server-side XML Injection. See report posted in Discord.

**Comment by pizzaluc** [comment]
This issue seem to have been completed, will close
