### ISSUE TITLE
White Hat Attack The Next Team

### ISSUE THREAD

**Issue by Herover** [Herover/itu-devops-h#127]
[Group i](https://github.com/itu-devops/lecture_notes/blob/master/repositories.py#L59)

**Comment by erentomurcuk** [comment]
WMAP Test has been completed, no vulnerabilities found
[TerminalOutput_WMAP.txt](https://github.com/Herover/itu-devops-h/files/8404478/TerminalOutput_WMAP.txt)
.

**Comment by erentomurcuk** [comment]
Skipfish scan has been completed, terminal output and skipfish output can be found here
[skipfishOut.tar.gz](https://github.com/Herover/itu-devops-h/fil
[TerminalOutput_Skipfish.txt](https://github.com/Herover/itu-devops-h/files/8404498/TerminalOutput_Skipfish.txt)
es/8404497/skipfishOut.tar.gz)

**Comment by pizzaluc** [comment]
This issue seem to have been fixed, will close
