### ISSUE TITLE
Setup docker containerization

### ISSUE THREAD

**Issue by pizzaluc** [Herover/itu-devops-h#43]
Create docker image automatically when pushing to main

Upload it automatically to some docker image hub, so the server can fetch the latest image

**Comment by Herover** [comment]
Something to consider is if we should use [Docker Hub](https://www.docker.com/pricing) or [Digital Oceans Container Registry](https://www.digitalocean.com/products/container-registry).

I think Digital Ocean has a edge since we can get a free private repo but haven't looked very deep into it :)
