### ISSUE TITLE
Upgrade VelocityTools 2.0 to 3.1

### ISSUE THREAD

**Issue by Herover** [Herover/itu-devops-h#49]
The version we have haven't been updated for 12 years. It might be enough to just replace the dependency, see:
https://velocity.apache.org/tools/devel/upgrading.html
https://mvnrepository.com/artifact/org.apache.velocity.tools/velocity-tools-parent/3.1
https://velocity.apache.org/tools/3.1/apidocs/org/apache/velocity/tools/generic/DateTool.html

**Comment by erentomurcuk** [comment]
I've been checking this out, for some reason `org.apache.velocity.tools.` doesn't work with 3.1 dependency. Searching for workarounds without adding 2.0 at the same time.
