### ISSUE TITLE
Fix new messages being invisible with second account

### ISSUE THREAD

**Issue by smilladion** [Herover/itu-devops-h#60]
Sign up > Sign in > Post message > Sign out > Sign up > Sign in > Post message 
This path messes up the user's timeline. You cannot see the messages you post with the second account, and you can see the messages of the first account on your own timeline without having followed them. Following and unfollowing other accounts also doesn't work correctly.

**Comment by erentomurcuk** [comment]
acquired the same issue just with `Sign up > Sign in > Post message` path right after starting the application with an existing database

**Comment by erentomurcuk** [comment]
![image](https://user-images.githubusercontent.com/54647908/155621470-74a4dfff-0b35-4edc-958a-92f398acbafc.png)
t3 follows t1 and t2

![image](https://user-images.githubusercontent.com/54647908/155621557-3e4f62f5-e015-40e2-b4f6-129218e502ed.png)
t2 only follows t1

![image](https://user-images.githubusercontent.com/54647908/155621618-c4728687-34a7-4653-9605-8ffa464bda26.png)
t1 doesn't follow anyone

![image](https://user-images.githubusercontent.com/54647908/155621659-537249ad-2e12-4b9f-bdc8-e6ecf25e85df.png)
public timeline from view of t1

![image](https://user-images.githubusercontent.com/54647908/155621689-93a78a56-936f-4848-b8ca-42d4386abaa6.png)
public timeline without logging in
